### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by opoplawski** [conda-forge/jupyterhub-feedstock#13]
Installed jupyterhub 0.8.1 but it failed with:
```
jupyterhub[14149]: ImportError: No module named 'alembic'
```

**Comment by opoplawski** [comment]
Hmm, dep is there and installed (0.9.6), but for some reason it isn't finding it.

**Comment by minrk** [comment]
@opoplawski what do you get from `python -c 'import alembic'`?

**Comment by opoplawski** [comment]
Turns out this was an issue with using an old version of the conda package manager and alembic was not being installed into the proper location.
