### ISSUE TITLE
Package without configurable-http-proxy?

### ISSUE THREAD

**Issue by jcrist** [conda-forge/jupyterhub-feedstock#23]
It would be nice to have a minimal installation that does not include things that only the `jupyterhub` server needs (`configurable-http-proxy`, etc...) to minimize the packages installed in a notebook environment (where `singleuser` runs). This would be useful for installations using spawners where the jupyterhub server and singleuser notebooks run on separate computers (and thus have separate environments).

Dask handles this by having a `dask-core` package on conda-forge that only includes the core dependencies, and then a `dask` package that includes everything. Perhaps a similar model would work here.

**Comment by minrk** [comment]
There's now a jupyterhub-base (only the Python package) and jupyterhub-singleuser (Python package plus notebook)

**Comment by jcrist** [comment]
Thanks Min!
