### ISSUE TITLE
0.7 py35 builds are big

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/jupyterhub-feedstock#4]
The python [3.5 builds](https://anaconda.org/conda-forge/jupyterhub/files?version=0.7.0) are >2x the size of all 0.6.1 builds and the 0.7.0 py34 builds. They appear to be shipping the `__pycache__` of some of stdlib, pip, certifi and setuptools.

Two things I tried locally appeared to get the size back down to the size of the 3.4 builds:
- actually list out all the deps from `run`: seems odd
- go back to invoking `setup.py install --single-version-externally-managed --record=record.txt`

...both still left 25k in `lib/python3.5/setuptools/command/__pycache__/develop.pyc`

**Comment by minrk** [comment]
Looks like this is a conda-build issue, and tracked upstream https://github.com/conda-forge/setuptools-feedstock/issues/18 and https://github.com/conda/conda-build/issues/1301. Bumping conda-build version should fix it, once the conda-forge tooling does so, and nothing should change in the recipe.
